apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quantlix

resources:
  - ../../base
  - api-secret.yaml

# Dev: local images, MOCK_K8S=true (default in base)
patches:
  - target:
      kind: Deployment
      name: grafana
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "http://grafana.quantlix.local"
