apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quantlix

resources:
  - namespace.yaml
  - letsencrypt-issuer.yaml
  - postgres/secret.yaml
  - postgres/deployment.yaml
  - redis/deployment.yaml
  - minio/deployment.yaml
  - api/deployment.yaml
  - orchestrator/rbac.yaml
  - orchestrator/deployment.yaml
  - prometheus/configmap.yaml
  - prometheus/deployment.yaml
  - loki/deployment.yaml
  - promtail/configmap.yaml
  - promtail/deployment.yaml
  - grafana/dashboards-configmap.yaml
  - grafana/deployment.yaml
  - ingress.yaml
